#! /usr/bin/env bash

################################################################################

panic()
{
	echo "ERROR: $*"
	exit 1
}

list_files()
{
    find "$1" -printf "%M %u %P\n" | sort
}

get_clang_version()
{
	local program="${1:-clang++}"
	"$program" --version | awk '
		(NR==1){
			for (i = 1; i <= NF; ++i) {
				if (tolower($i) == "version") {
					++i;
					print $i;
					break;
				}
			}
		}
	'
}

################################################################################

self_program="$(realpath "$0")" || \
  panic "realpath failed"
self_dir="$(dirname "$self_program")" || \
  panic "dirname failed"

top_dir="$self_dir/../.."

verbose=0
matrix_os=

while getopts vs: option; do
	case "$option" in
	v)
		verbose=$((verbose + 1));;
	s)
		matrix_os="$OPTARG";;
	*)
		usage "invalid option $option"
		break
		;;
	esac
done
shift $((OPTIND - 1))


build_options=()
build_options+=(--num-jobs 4)
case "$matrix_os" in

ubuntu-*)
	case "$matrix_os" in
	*-22.04)
		build_options+=(--demo)
		;;
	esac
	export PATH="/usr/lib/llvm-15/bin:$PATH"
	export CMAKE_PREFIX_PATH="/usr/lib/llvm-15/lib/cmake/llvm:$CMAKE_PREFIX_PATH"
	export LD_LIBRARY_PATH="/usr/lib/llvm-15/lib:$LD_LIBRARY_PATH"
	case "$CC" in
	*clang*)
		export CC="clang"
		export CXX="clang++"
		;;
	*gcc*)
		case "$matrix_os" in
		*-20.04)
			export CC="gcc-10"
			export CXX="g++-10"
			;;
		esac
		;;
	esac
	;;

macos-*)
	# TODO: How to find the version number?
	clang_version=15.0.7
	llvm_dir=/usr/local/Cellar/llvm/$clang_version
	export PATH=/usr/local/opt/llvm/bin:$llvm_dir/bin:$PATH
	export CMAKE_PREFIX_PATH="$llvm_dir/lib/cmake/llvm:$CMAKE_PREFIX_PATH"
	export LD_LIBRARY_PATH="$llvm_dir/lib:$LD_LIBRARY_PATH"
	#export CL_CLANG_INCLUDE_DIR=/usr/local/opt/llvm@15/lib/clang/$clang_version/include
	build_options+=(--no-enable-asan-user-poisoning)
	;;

*)
	panic "invalid matrix OS"
	;;

esac

if [ "$verbose" -ge 1 ]; then
	cat <<- EOF
	============================================================
	CC: $CC
	============================================================
	CXX: $CXX
	============================================================
	PATH: $PATH
	============================================================
	LD_LIBRARY_PATH: $LD_LIBRARY_PATH
	============================================================
	CMAKE_PREFIX_PATH: $CMAKE_PREFIX_PATH
	============================================================
	Clang version:
	$(clang++ --version)
	$(clang --version)
	============================================================
	GCC version:
	$(g++ --version)
	$(gcc --version)
	============================================================
	Clang default version of C++ standard:
	$(g++ -dM -E -x c++  /dev/null | grep -F __cplusplus)
	============================================================
	GCC default version of C++ standard:
	$(clang++ -dM -E -x c++  /dev/null | grep -F __cplusplus)
	============================================================
	EOF
fi

"$top_dir/build" \
  --verbose \
  --clean \
  --build \
  --verbose-makefile \
  --fmt \
  --debug \
  --asan \
  --ubsan \
  "${build_options[@]}" \
  || panic "build failed"
