#! /usr/bin/env bash

################################################################################

panic()
{
	echo "ERROR: $*"
	exit 1
}

list_directory_recursive()
{
    find "$1" -printf "%M %u %P\n" | sort
}

list_directory()
{
	local options=()
	while [ $# -gt 1 ]; do
		options+=("$1")
		shift 1
	done
	echo "directory: $1" || return 1
    ls -l "${options[@]}" "$1" || return 1
}

################################################################################

usage()
{
	echo "BAD USAGE: $*"
	exit 2
}

verbose=0
matrix_os=

while getopts vs: option; do
	case "$option" in
	v)
		verbose=$((verbose + 1));;
	s)
		matrix_os="$OPTARG";;
	*)
		usage "invalid option $option"
		break
		;;
	esac
done
shift $((OPTIND - 1))

if [ "$verbose" -ge 2 ]; then
	set -xv
fi

if [ -z "$matrix_os" ]; then
	panic "GitHub Actions matrix OS not specified"
fi

echo "PREBUILD MATRIX OS: $matrix_os"

case "$matrix_os" in

ubuntu-*)

	llvm_packages=(
		libllvm-15-ocaml-dev
		libllvm15
		llvm-15
		llvm-15-dev
		llvm-15-doc
		llvm-15-examples
		llvm-15-runtime
		clang-15
		clang-tools-15
		clang-15-doc
		libclang-common-15-dev
		libclang-15-dev
		libclang1-15
		clang-format-15
		python3-clang-15
		clangd-15
		clang-tidy-15
		libfuzzer-15-dev
		lldb-15
		lld-15
		libc++-15-dev
		libc++abi-15-dev
		libomp-15-dev
		libclc-15-dev
		libunwind-15-dev
		libmlir-15-dev
		mlir-15-tools
		libbolt-15-dev
		bolt-15
	)

	case "$matrix_os" in

	*-22.04)
		repos=(
			"deb http://apt.llvm.org/jammy/ llvm-toolchain-jammy-15 main"
		)
		other_packages=(
			gcc-11
			libboost-all-dev
			python3
		)
		;;

	*-20.04)
		repos=(
			"deb http://apt.llvm.org/focal/ llvm-toolchain-focal-15 main"
		)
		other_packages=(
			gcc-10
			libboost-all-dev
			python3
		)
		;;

	*)
		panic "invalid matrix OS value $matrix_os"
		;;

	esac

	wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | \
	  sudo apt-key add -

	for repo in "${repos[@]}"; do
		echo "Adding APT repository: $repo"
		sudo add-apt-repository "$repo" || \
		  panic "add-apt-repository failed for $repo"
	done

	echo "Updating packages"
	sudo apt-get update || \
	  panic "apt-get update failed"

	echo "Installing packages: ${other_packages[*]}"
	sudo apt-get install "${other_packages[@]}" "${llvm_packages[@]}" || \
	  panic "apt-get install failed"

	case "$matrix_os" in
	*-22.04)
		if [ "$verbose" -ge 1 ]; then
			list_directory    /usr/lib64
			list_directory    /usr/lib
			list_directory    /usr/lib/cmake/clang-15
			list_directory -L /usr/lib/cmake/clang-15
			list_directory    /lib/cmake/clang-15
			list_directory -L /lib/cmake/clang-15
			list_directory    /usr/include/llvm-15/llvm
			list_directory    /usr/lib/llvm-15/lib
			list_directory    /usr/lib/llvm-15/lib/clang
			list_directory    /usr/lib/llvm-15/lib/clang/15
			list_directory    /usr/lib/llvm-15/lib/clang/15.0.6
			list_directory    /usr/lib/llvm-15/lib/cmake/llvm # CMake config
			list_directory    /usr/lib/llvm-15/lib/cmake/clang
		fi
	esac

	;;

macos-*)

	#export HOMEBREW_NO_AUTO_UPDATE=1
	#export HOMEBREW_NO_ANALYTICS=1
	export HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK=1
	export HOMEBREW_NO_INSTALL_CLEANUP=1
	brew update || panic "brew update failed"
	brew install coreutils || panic "brew install coreutils failed"
	if [ 1 -ne 0 ]; then
		find /usr/local/bin -lname '*/Library/Frameworks/Python.framework/*' \
		  -delete
		sudo rm -rf /Library/Frameworks/Python.framework/
		brew install --force python3 && \
		  brew unlink python3 && \
		  brew unlink python3 && \
		  brew link --overwrite python3 || panic
	fi
	brew install boost || panic "brew install boost failed"
	brew install llvm@15 || panic "brew install failed"
	#brew install lit || panic "brew install failed"

	list_directory -l /usr/local/Cellar/llvm/15/bin/clang
	list_directory -l /usr/local/Cellar
	list_directory -l /usr/local/opt
	#list_directory -l /usr/local/opt/llvm
	#list_directory -l /usr/local/opt/clang

	list_directory -l /usr/local/opt/llvm@15/bin
	list_directory -l /usr/local/opt/llvm@15/include
	list_directory -l /usr/local/opt/llvm@15/include/clang
	#list_directory -l /usr/local/opt/llvm@15/include/clang/15.0.6
	#list_directory -l /usr/local/opt/llvm@15/lib
	#list_directory -l /usr/local/opt/llvm@15/lib/clang
	list_directory -l /usr/local/opt/llvm@15/lib/clang/15.0.6/include

	;;

*)
	panic "invalid OS $matrix_os"
	;;

esac

exit 0
