#! /usr/bin/env bash

################################################################################

cmake_source_dir="@CMAKE_SOURCE_DIR@"
cmake_binary_dir="@CMAKE_BINARY_DIR@"

panic()
{
	echo "ERROR: $*"
	exit 1
}

run_command()
{
	echo "RUNNING: $*"
	"$@"
	local status=$?
	echo "EXIT STATUS: $status"
	return "$status"
}

source_dir="$cmake_source_dir"
build_dir="$cmake_binary_dir"
data_dir="$source_dir/data"
run_clang_tool="$source_dir/run_clang_tool"
real_data_dir="@DATA_DIR@"

################################################################################

command_terminator="__EOC__"

default_commands=(
	fixed "$command_terminator"
	json "$command_terminator"
	adjuster -a 0 "$command_terminator"
	adjuster -a 1 "$command_terminator"
	adjuster -a 2 "$command_terminator"
	response 0 "$command_terminator"
	response 1 "$command_terminator"
)


if [ $# -ge 1 ]; then
	commands=("$@" "$command_terminator")
else
	commands=("${default_commands[@]}")
fi

while [ "${#commands[@]}" -ne 0 ]; do

	demo=("${commands[0]}")

	# Pop the first element from the array.
	unset commands[0]
	commands=("${commands[@]}")

	options=()
	while [ "${#commands[@]}" -ne 0 ]; do

		option=("${commands[0]}")

		# Pop the first element from the array.
		unset commands[0]
		commands=("${commands[@]}")

		if [ "x$option" == "x$command_terminator" ]; then
			break
		fi
		options+=("$option")

	done

	echo "============================================================"
	echo "demo: $demo"
	echo "options: ${options[*]}"
	echo "============================================================"

	case "$demo" in

	json)
		run_command \
		  "$build_dir/json_database" \
		  "$real_data_dir/compile_commands-simple.json" \
		  "${options[@]}" || \
		  panic "tool failed"
		;;

	fixed)
		run_command \
		  "$build_dir/fixed_database" \
		  "$real_data_dir/fixed_compilation_database.txt" \
		  hello.cpp \
		  goodbye.cpp \
		  "${options[@]}" || \
		  panic "tool failed"
		;;

	adjuster)
		base_options=(
		  #-f "$real_data_dir/fixed_compilation_database.txt"
		  -j "$real_data_dir/compile_commands-simple.json"
		  -a 0
		)
		run_command \
		  "$build_dir/arg_adjuster" \
		  "${base_options[@]}" \
		  "${options[@]}" \
		  hello.cpp || \
		  panic "tool failed"
		;;

	response)
		run_command \
		  "$build_dir/response" \
		  "$real_data_dir/compile_commands-rsp.json" \
		  "${options[@]}" || \
		  panic "tool failed"
		;;

	esac

done
